package com.cm.dao.model.wechatmanage;

import java.io.Serializable;

public class SysConf implements Serializable {
    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 系统参数key
     * @table : wechatmanage..sys_conf
     * @column : SYS_KEY :VARCHAR
     */
    private String sysKey;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 系统参数值
     * @table : wechatmanage..sys_conf
     * @column : SYS_VALUE :VARCHAR
     */
    private String sysValue;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 系统参数描述
     * @table : wechatmanage..sys_conf
     * @column : SYS_DESC :VARCHAR
     */
    private String sysDesc;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 系统参数排序
     * @table : wechatmanage..sys_conf
     * @column : SYS_SORT :INTEGER
     */
    private Integer sysSort;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 系统参数标识
     * @table : wechatmanage..sys_conf
     * @column : SYS_FLAG :INTEGER
     */
    private Integer sysFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechatmanage..sys_conf
     *
     * @mbggenerated Tue Dec 20 14:01:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_conf.SYS_KEY:[系统参数key]
     */
    public String getSysKey() {
        return sysKey;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param sysKey  系统参数key
     */
    public void setSysKey(String sysKey) {
        this.sysKey = sysKey == null ? null : sysKey.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_conf.SYS_VALUE:[系统参数值]
     */
    public String getSysValue() {
        return sysValue;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param sysValue  系统参数值
     */
    public void setSysValue(String sysValue) {
        this.sysValue = sysValue == null ? null : sysValue.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_conf.SYS_DESC:[系统参数描述]
     */
    public String getSysDesc() {
        return sysDesc;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param sysDesc  系统参数描述
     */
    public void setSysDesc(String sysDesc) {
        this.sysDesc = sysDesc == null ? null : sysDesc.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_conf.SYS_SORT:[系统参数排序]
     */
    public Integer getSysSort() {
        return sysSort;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param sysSort  系统参数排序
     */
    public void setSysSort(Integer sysSort) {
        this.sysSort = sysSort;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_conf.SYS_FLAG:[系统参数标识]
     */
    public Integer getSysFlag() {
        return sysFlag;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param sysFlag  系统参数标识
     */
    public void setSysFlag(Integer sysFlag) {
        this.sysFlag = sysFlag;
    }
}