package com.cm.dao.model.wechatmanage;

import java.io.Serializable;

public class SysFuncUrlKey implements Serializable {
    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 功能id
     * @table : wechatmanage..sys_func_url
     * @column : FUNCID :INTEGER
     */
    private Integer funcid;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 功能请求url
     * @table : wechatmanage..sys_func_url
     * @column : URLID :INTEGER
     */
    private Integer urlid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechatmanage..sys_func_url
     *
     * @mbggenerated Tue Dec 20 14:01:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_func_url.FUNCID:[功能id]
     */
    public Integer getFuncid() {
        return funcid;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param funcid  功能id
     */
    public void setFuncid(Integer funcid) {
        this.funcid = funcid;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_func_url.URLID:[功能请求url]
     */
    public Integer getUrlid() {
        return urlid;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param urlid  功能请求url
     */
    public void setUrlid(Integer urlid) {
        this.urlid = urlid;
    }
}