package com.cm.dao.model.wechatmanage;

import java.io.Serializable;

public class SysFunc implements Serializable {
    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 功能id
     * @table : wechatmanage..sys_func
     * @column : FUNCID :INTEGER
     */
    private Integer funcid;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 功能菜单id
     * @table : wechatmanage..sys_func
     * @column : MENUID :INTEGER
     */
    private Integer menuid;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 操作id
     * @table : wechatmanage..sys_func
     * @column : OPERID :INTEGER
     */
    private Integer operid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechatmanage..sys_func
     *
     * @mbggenerated Tue Dec 20 14:01:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_func.FUNCID:[功能id]
     */
    public Integer getFuncid() {
        return funcid;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param funcid  功能id
     */
    public void setFuncid(Integer funcid) {
        this.funcid = funcid;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_func.MENUID:[功能菜单id]
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param menuid  功能菜单id
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_func.OPERID:[操作id]
     */
    public Integer getOperid() {
        return operid;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param operid  操作id
     */
    public void setOperid(Integer operid) {
        this.operid = operid;
    }
}