package com.cm.dao.model.wechatmanage;

import java.io.Serializable;
import java.util.Date;

public class SysLogOper implements Serializable {
    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 用户id
     * @table : wechatmanage..sys_log_oper
     * @column : USERID :VARCHAR
     */
    private String userid;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 用户名称
     * @table : wechatmanage..sys_log_oper
     * @column : USERNAME :VARCHAR
     */
    private String username;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 用户操作id
     * @table : wechatmanage..sys_log_oper
     * @column : operid :INTEGER
     */
    private Integer operid;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 用户操作名称
     * @table : wechatmanage..sys_log_oper
     * @column : OPERNAME :VARCHAR
     */
    private String opername;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 操作参数
     * @table : wechatmanage..sys_log_oper
     * @column : PARAMS :VARCHAR
     */
    private String params;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 操作结果
     * @table : wechatmanage..sys_log_oper
     * @column : SUCCESS :INTEGER
     */
    private Integer success;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 备注
     * @table : wechatmanage..sys_log_oper
     * @column : REMARK :VARCHAR
     */
    private String remark;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 操作时间
     * @table : wechatmanage..sys_log_oper
     * @column : CREATE_TIME :TIMESTAMP
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechatmanage..sys_log_oper
     *
     * @mbggenerated Tue Dec 20 14:01:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_log_oper.USERID:[用户id]
     */
    public String getUserid() {
        return userid;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param userid  用户id
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_log_oper.USERNAME:[用户名称]
     */
    public String getUsername() {
        return username;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param username  用户名称
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_log_oper.operid:[用户操作id]
     */
    public Integer getOperid() {
        return operid;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param operid  用户操作id
     */
    public void setOperid(Integer operid) {
        this.operid = operid;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_log_oper.OPERNAME:[用户操作名称]
     */
    public String getOpername() {
        return opername;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param opername  用户操作名称
     */
    public void setOpername(String opername) {
        this.opername = opername == null ? null : opername.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_log_oper.PARAMS:[操作参数]
     */
    public String getParams() {
        return params;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param params  操作参数
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_log_oper.SUCCESS:[操作结果]
     */
    public Integer getSuccess() {
        return success;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param success  操作结果
     */
    public void setSuccess(Integer success) {
        this.success = success;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_log_oper.REMARK:[备注]
     */
    public String getRemark() {
        return remark;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param remark  备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_log_oper.CREATE_TIME:[操作时间]
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param createTime  操作时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}