package com.cm.dao.model.wechatmanage;

import java.io.Serializable;

public class SysMenu implements Serializable {
    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 系统菜单id
     * @table : wechatmanage..sys_menu
     * @column : MENUID :INTEGER
     */
    private Integer menuid;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 父菜单id
     * @table : wechatmanage..sys_menu
     * @column : PARENTID :INTEGER
     */
    private Integer parentid;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 菜单名称
     * @table : wechatmanage..sys_menu
     * @column : MENUITEM :VARCHAR
     */
    private String menuitem;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 菜单排序
     * @table : wechatmanage..sys_menu
     * @column : SORT :INTEGER
     */
    private Integer sort;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 菜单请求url
     * @table : wechatmanage..sys_menu
     * @column : URL :VARCHAR
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechatmanage..sys_menu
     *
     * @mbggenerated Tue Dec 20 14:01:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_menu.MENUID:[系统菜单id]
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param menuid  系统菜单id
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_menu.PARENTID:[父菜单id]
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param parentid  父菜单id
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_menu.MENUITEM:[菜单名称]
     */
    public String getMenuitem() {
        return menuitem;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param menuitem  菜单名称
     */
    public void setMenuitem(String menuitem) {
        this.menuitem = menuitem == null ? null : menuitem.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_menu.SORT:[菜单排序]
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param sort  菜单排序
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_menu.URL:[菜单请求url]
     */
    public String getUrl() {
        return url;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param url  菜单请求url
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}