package com.cm.dao.model.wechatmanage;

import java.io.Serializable;

public class SysOperate implements Serializable {
    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 操作id
     * @table : wechatmanage..sys_operate
     * @column : OPERID :INTEGER
     */
    private Integer operid;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 操作名称
     * @table : wechatmanage..sys_operate
     * @column : OPERNAME :VARCHAR
     */
    private String opername;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 操作key
     * @table : wechatmanage..sys_operate
     * @column : OPERKEY :VARCHAR
     */
    private String operkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechatmanage..sys_operate
     *
     * @mbggenerated Tue Dec 20 14:01:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_operate.OPERID:[操作id]
     */
    public Integer getOperid() {
        return operid;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param operid  操作id
     */
    public void setOperid(Integer operid) {
        this.operid = operid;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_operate.OPERNAME:[操作名称]
     */
    public String getOpername() {
        return opername;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param opername  操作名称
     */
    public void setOpername(String opername) {
        this.opername = opername == null ? null : opername.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_operate.OPERKEY:[操作key]
     */
    public String getOperkey() {
        return operkey;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param operkey  操作key
     */
    public void setOperkey(String operkey) {
        this.operkey = operkey == null ? null : operkey.trim();
    }
}