package com.cm.dao.model.wechatmanage;

import java.io.Serializable;

public class SysRole implements Serializable {
    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 系统角色id
     * @table : wechatmanage..sys_role
     * @column : ROLEID :INTEGER
     */
    private Integer roleid;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 角色名称
     * @table : wechatmanage..sys_role
     * @column : ROLENAME :VARCHAR
     */
    private String rolename;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 是否禁用；1:禁用；0:启用
     * @table : wechatmanage..sys_role
     * @column : DISABLE :INTEGER
     */
    private Integer disable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechatmanage..sys_role
     *
     * @mbggenerated Tue Dec 20 14:01:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_role.ROLEID:[系统角色id]
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param roleid  系统角色id
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_role.ROLENAME:[角色名称]
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param rolename  角色名称
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_role.DISABLE:[是否禁用；1:禁用；0:启用]
     */
    public Integer getDisable() {
        return disable;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param disable  是否禁用；1:禁用；0:启用
     */
    public void setDisable(Integer disable) {
        this.disable = disable;
    }
}