package com.cm.dao.model.wechatmanage;

import java.io.Serializable;

public class SysRoleFuncKey implements Serializable {
    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 系统功能id
     * @table : wechatmanage..sys_role_func
     * @column : FUNCID :INTEGER
     */
    private Integer funcid;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 角色id
     * @table : wechatmanage..sys_role_func
     * @column : ROLEID :INTEGER
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechatmanage..sys_role_func
     *
     * @mbggenerated Tue Dec 20 14:01:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_role_func.FUNCID:[系统功能id]
     */
    public Integer getFuncid() {
        return funcid;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param funcid  系统功能id
     */
    public void setFuncid(Integer funcid) {
        this.funcid = funcid;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_role_func.ROLEID:[角色id]
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param roleid  角色id
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}