package com.cm.dao.model.wechatmanage;

import java.io.Serializable;

public class SysUserRoleKey implements Serializable {
    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 角色id
     * @table : wechatmanage..sys_user_role
     * @column : ROLEID :INTEGER
     */
    private Integer roleid;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 用户id
     * @table : wechatmanage..sys_user_role
     * @column : USERID :VARCHAR
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechatmanage..sys_user_role
     *
     * @mbggenerated Tue Dec 20 14:01:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_user_role.ROLEID:[角色id]
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param roleid  角色id
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..sys_user_role.USERID:[用户id]
     */
    public String getUserid() {
        return userid;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param userid  用户id
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }
}