package com.cm.dao.model.wechatmanage;

import java.io.Serializable;

public class WxModule implements Serializable {
    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 模块id
     * @table : wechatmanage..wx_module
     * @column : MODULEID :VARCHAR
     */
    private String moduleid;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 模块名称
     * @table : wechatmanage..wx_module
     * @column : MODULENAME :VARCHAR
     */
    private String modulename;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 模块对应处理类
     * @table : wechatmanage..wx_module
     * @column : MODULEPATH :VARCHAR
     */
    private String modulepath;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 模块标识 ，暂无
     * @table : wechatmanage..wx_module
     * @column : MODULEFLAG :INTEGER
     */
    private Integer moduleflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechatmanage..wx_module
     *
     * @mbggenerated Tue Dec 20 14:01:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..wx_module.MODULEID:[模块id]
     */
    public String getModuleid() {
        return moduleid;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param moduleid  模块id
     */
    public void setModuleid(String moduleid) {
        this.moduleid = moduleid == null ? null : moduleid.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..wx_module.MODULENAME:[模块名称]
     */
    public String getModulename() {
        return modulename;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param modulename  模块名称
     */
    public void setModulename(String modulename) {
        this.modulename = modulename == null ? null : modulename.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..wx_module.MODULEPATH:[模块对应处理类]
     */
    public String getModulepath() {
        return modulepath;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param modulepath  模块对应处理类
     */
    public void setModulepath(String modulepath) {
        this.modulepath = modulepath == null ? null : modulepath.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechatmanage..wx_module.MODULEFLAG:[模块标识 ，暂无]
     */
    public Integer getModuleflag() {
        return moduleflag;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param moduleflag  模块标识 ，暂无
     */
    public void setModuleflag(Integer moduleflag) {
        this.moduleflag = moduleflag;
    }
}