package com.cm.dao.model.wechat;

import java.io.Serializable;

public class WxMenu implements Serializable {
    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 菜单id
     * @table : wechat..wx_menu
     * @column : ID :INTEGER
     */
    private Integer id;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 父菜单id
     * @table : wechat..wx_menu
     * @column : PARENT_ID :VARCHAR
     */
    private String parentId;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 菜单名称
     * @table : wechat..wx_menu
     * @column : NAME :VARCHAR
     */
    private String name;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 菜单类型
     * @table : wechat..wx_menu
     * @column : TYPE :VARCHAR
     */
    private String type;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 菜单内容
     * @table : wechat..wx_menu
     * @column : CONTENT :VARCHAR
     */
    private String content;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 是否与微信同步；1，已同步；0，未同步
     * @table : wechat..wx_menu
     * @column : POST_FLAG :INTEGER
     */
    private Integer postFlag;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 是否删除
     * @table : wechat..wx_menu
     * @column : DELETE_FLAG :INTEGER
     */
    private Integer deleteFlag;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 菜单排序
     * @table : wechat..wx_menu
     * @column : SORT :INTEGER
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechat..wx_menu
     *
     * @mbggenerated Tue Dec 20 14:01:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * 微信用户所属服务号应用id
     */
    private String accountid;
    /**
     * 微信用户所属服务号应用schema
     */
    private String schema;
    
    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_menu.ID:[菜单id]
     */
    public Integer getId() {
        return id;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param id  菜单id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_menu.PARENT_ID:[父菜单id]
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param parentId  父菜单id
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_menu.NAME:[菜单名称]
     */
    public String getName() {
        return name;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param name  菜单名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_menu.TYPE:[菜单类型]
     */
    public String getType() {
        return type;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param type  菜单类型
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_menu.CONTENT:[菜单内容]
     */
    public String getContent() {
        return content;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param content  菜单内容
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_menu.POST_FLAG:[是否与微信同步；1，已同步；0，未同步]
     */
    public Integer getPostFlag() {
        return postFlag;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param postFlag  是否与微信同步；1，已同步；0，未同步
     */
    public void setPostFlag(Integer postFlag) {
        this.postFlag = postFlag;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_menu.DELETE_FLAG:[是否删除]
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param deleteFlag  是否删除
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_menu.SORT:[菜单排序]
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param sort  菜单排序
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
    
    /**
     * 微信用户所属服务号应用id
     */
	public String getAccountid() {
		return accountid;
	}

	/**
     * 微信用户所属服务号应用id
     */
	public void setAccountid(String accountid) {
		this.accountid = accountid;
	}

	/**
     * 微信用户所属服务号应用schema
     */
	public String getSchema() {
		return schema;
	}

	/**
     * 微信用户所属服务号应用schema
     */
	public void setSchema(String schema) {
		this.schema = schema;
	}
}