package com.cm.dao.model.wechat;

import java.io.Serializable;
import java.util.Date;

public class WxUser implements Serializable {
    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 用户id
     * @table : wechat..wx_user
     * @column : ID :INTEGER
     */
    private Integer id;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 用户标识，可修改一次。唯一
     * @table : wechat..wx_user
     * @column : USERID :VARCHAR
     */
    private String userid;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 微信用户openid，对当前公众号唯一
     * @table : wechat..wx_user
     * @column : OPENID :VARCHAR
     */
    private String openid;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 微信用户综合id，对当前同一开发平台不同应用唯一
     * @table : wechat..wx_user
     * @column : unionid :VARCHAR
     */
    private String unionid;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 微信用户名称
     * @table : wechat..wx_user
     * @column : NICKNAME :VARCHAR
     */
    private String nickname;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 微信组别 ID
     * @table : wechat..wx_user
     * @column : GROUPID :INTEGER
     */
    private Integer groupid;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 用户所在国家
     * @table : wechat..wx_user
     * @column : COUNTRY :VARCHAR
     */
    private String country;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 用户所在省份
     * @table : wechat..wx_user
     * @column : PROVINCE :VARCHAR
     */
    private String province;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 用户所在城市
     * @table : wechat..wx_user
     * @column : CITY :VARCHAR
     */
    private String city;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 用户性别 1:男；2:女；0:未知
     * @table : wechat..wx_user
     * @column : SEX :INTEGER
     */
    private Integer sex;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 用户头像url地址；最后一个数值代表正方形头像大小（有0、46、64、96、132数值可选，0代表640*640正方形头像），用户没有头像时该项为空。若用户更换头像，原有头像URL将失效。
     * @table : wechat..wx_user
     * @column : IMAGEURL :VARCHAR
     */
    private String imageurl;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 用户的语言，简体中文为zh_CN
     * @table : wechat..wx_user
     * @column : LANGUAGE :VARCHAR
     */
    private String language;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 用户是否关注 微信号 ；0:未关注；1:已关注
     * @table : wechat..wx_user
     * @column : SUBSCRIBE :INTEGER
     */
    private Integer subscribe;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 用户关注时间 如果用户曾多次关注，则取最后关注时间
     * @table : wechat..wx_user
     * @column : SUBSCRIBETIME :TIMESTAMP
     */
    private Date subscribetime;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 微信关注类型: 1扫码 2搜索
     * @table : wechat..wx_user
     * @column : SUBSCRIBETYPE :INTEGER
     */
    private Integer subscribetype;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 公众号运营者对粉丝的备注，公众号运营者可在微信公众平台用户管理界面对粉丝添加备注
     * @table : wechat..wx_user
     * @column : REMARK :VARCHAR
     */
    private String remark;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 用户手机号
     * @table : wechat..wx_user
     * @column : MOBILEPHONE :VARCHAR
     */
    private String mobilephone;

    /**
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     * 用户更新信息时间
     * @table : wechat..wx_user
     * @column : UPDATETIME :TIMESTAMP
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechat..wx_user
     *
     * @mbggenerated Tue Dec 20 14:01:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * 微信用户所属服务号应用id
     */
    private String accountid;
    /**
     * 微信用户所属服务号应用schema
     */
    private String schema;
    
    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_user.ID:[用户id]
     */
    public Integer getId() {
        return id;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param id  用户id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_user.USERID:[用户标识，可修改一次。唯一]
     */
    public String getUserid() {
        return userid;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param userid  用户标识，可修改一次。唯一
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_user.OPENID:[微信用户openid，对当前公众号唯一]
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param openid  微信用户openid，对当前公众号唯一
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_user.unionid:[微信用户综合id，对当前同一开发平台不同应用唯一]
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param unionid  微信用户综合id，对当前同一开发平台不同应用唯一
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_user.NICKNAME:[微信用户名称]
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param nickname  微信用户名称
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_user.GROUPID:[微信组别 ID]
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param groupid  微信组别 ID
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_user.COUNTRY:[用户所在国家]
     */
    public String getCountry() {
        return country;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param country  用户所在国家
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_user.PROVINCE:[用户所在省份]
     */
    public String getProvince() {
        return province;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param province  用户所在省份
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_user.CITY:[用户所在城市]
     */
    public String getCity() {
        return city;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param city  用户所在城市
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_user.SEX:[用户性别 1:男；2:女；0:未知]
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param sex  用户性别 1:男；2:女；0:未知
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_user.IMAGEURL:[用户头像url地址；最后一个数值代表正方形头像大小（有0、46、64、96、132数值可选，0代表640*640正方形头像），用户没有头像时该项为空。若用户更换头像，原有头像URL将失效。]
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param imageurl  用户头像url地址；最后一个数值代表正方形头像大小（有0、46、64、96、132数值可选，0代表640*640正方形头像），用户没有头像时该项为空。若用户更换头像，原有头像URL将失效。
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl == null ? null : imageurl.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_user.LANGUAGE:[用户的语言，简体中文为zh_CN]
     */
    public String getLanguage() {
        return language;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param language  用户的语言，简体中文为zh_CN
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_user.SUBSCRIBE:[用户是否关注 微信号 ；0:未关注；1:已关注]
     */
    public Integer getSubscribe() {
        return subscribe;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param subscribe  用户是否关注 微信号 ；0:未关注；1:已关注
     */
    public void setSubscribe(Integer subscribe) {
        this.subscribe = subscribe;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_user.SUBSCRIBETIME:[用户关注时间 如果用户曾多次关注，则取最后关注时间]
     */
    public Date getSubscribetime() {
        return subscribetime;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param subscribetime  用户关注时间 如果用户曾多次关注，则取最后关注时间
     */
    public void setSubscribetime(Date subscribetime) {
        this.subscribetime = subscribetime;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_user.SUBSCRIBETYPE:[微信关注类型]
     */
    public Integer getSubscribetype() {
        return subscribetype;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param subscribetype  微信关注类型
     */
    public void setSubscribetype(Integer subscribetype) {
        this.subscribetype = subscribetype;
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_user.REMARK:[公众号运营者对粉丝的备注，公众号运营者可在微信公众平台用户管理界面对粉丝添加备注]
     */
    public String getRemark() {
        return remark;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param remark  公众号运营者对粉丝的备注，公众号运营者可在微信公众平台用户管理界面对粉丝添加备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_user.MOBILEPHONE:[用户手机号]
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param mobilephone  用户手机号
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }

    /**
     * get method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @return wechat..wx_user.UPDATETIME:[用户更新信息时间]
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * set method 
     * @author : lenovo
     * This field was generated by MyBatis Generator. Tue Dec 20 14:01:40 CST 2016
     *
     * @param updatetime  用户更新信息时间
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * 微信用户所属服务号应用id
     */
	public String getAccountid() {
		return accountid;
	}

	/**
     * 微信用户所属服务号应用id
     */
	public void setAccountid(String accountid) {
		this.accountid = accountid;
	}

	/**
     * 微信用户所属服务号应用schema
     */
	public String getSchema() {
		return schema;
	}

	/**
     * 微信用户所属服务号应用schema
     */
	public void setSchema(String schema) {
		this.schema = schema;
	}
    
}