package com.cm.dao.mapper.wechatmanage;

import com.cm.dao.model.wechatmanage.UserAccount;

public interface UserAccountMapper {
    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 插入数据库记录
     *
     * @param record
     * wechatmanage..user_account
     */
    int insert(UserAccount record);

    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 插入数据库记录
     *
     * @param record
     * wechatmanage..user_account
     */
    int insertSelective(UserAccount record);
}