package com.cm.dao.mapper.wechatmanage;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.cm.dao.model.wechatmanage.WxAccount;

public interface WxAccountMapper {
    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 根据主键删除数据库的记录
     *
     * @param id
     * wechatmanage..wx_account
     */
    int deleteByPrimaryKey(String id);

    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 插入数据库记录
     *
     * @param record
     * wechatmanage..wx_account
     */
    int insert(WxAccount record);

    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 插入数据库记录
     *
     * @param record
     * wechatmanage..wx_account
     */
    int insertSelective(WxAccount record);

    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 根据主键来更新部分数据库记录
     *
     * @param record
     * wechatmanage..wx_account
     */
    int updateByPrimaryKeySelective(WxAccount record);

    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 根据主键来更新数据库记录
     *
     * @param record
     * wechatmanage..wx_account
     */
    int updateByPrimaryKey(WxAccount record);
    
    /**
	 * 获取 wechat账号列表
	 * @author smile
	 * @date 2016年6月27日
	 * @return List<WechatAccount>  微信账号信息list
	 */
	public List<WxAccount> getWechatAccountList();
	
	/**
	 * 根据微信accountid 获取微信账号信息
	 * @author smile
	 * @date 2016年6月27日
	 * @param accountid
	 * @return WechatAccount 微信账号信息
	 */
	public WxAccount getWechatAccountById(@Param("id")String accountid);
}