package com.cm.dao.mapper.wechat;

import com.cm.dao.model.wechat.WxConf;

public interface WxConfMapper {
    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 根据主键删除数据库的记录
     *
     * @param wxKey
     * wechat..wx_conf
     */
    int deleteByPrimaryKey(String wxKey);

    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 插入数据库记录
     *
     * @param record
     * wechat..wx_conf
     */
    int insert(WxConf record);

    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 插入数据库记录
     *
     * @param record
     * wechat..wx_conf
     */
    int insertSelective(WxConf record);

    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 根据主键获取一条数据库记录
     *
     * @param wxKey
     * wechat..wx_conf
     */
    WxConf selectByPrimaryKey(String wxKey);

    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 根据主键来更新部分数据库记录
     *
     * @param record
     * wechat..wx_conf
     */
    int updateByPrimaryKeySelective(WxConf record);

    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 根据主键来更新数据库记录
     *
     * @param record
     * wechat..wx_conf
     */
    int updateByPrimaryKey(WxConf record);
}