package com.cm.dao.mapper.wechat;

import org.apache.ibatis.annotations.Param;

import com.cm.dao.model.wechat.WxQrcode;

public interface WxQrcodeMapper {
    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 根据主键删除数据库的记录
     *
     * @param qrcodeid
     * wechat..wx_qrcode
     */
    int deleteByPrimaryKey(@Param("schema")String schema,@Param("qrcodeid")String qrcodeid);

    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 插入数据库记录
     *
     * @param record
     * wechat..wx_qrcode
     */
    int insert(WxQrcode record);

    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 插入数据库记录
     *
     * @param record
     * wechat..wx_qrcode
     */
    int insertSelective(WxQrcode record);

    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 根据主键获取一条数据库记录
     *
     * @param qrcodeid
     * wechat..wx_qrcode
     */
    WxQrcode selectByPrimaryKey(@Param("schema")String schema,@Param("qrcodeid")String qrcodeid);

    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 根据主键来更新部分数据库记录
     *
     * @param record
     * wechat..wx_qrcode
     */
    int updateByPrimaryKeySelective(WxQrcode record);

    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 根据主键来更新数据库记录
     *
     * @param record
     * wechat..wx_qrcode
     */
    int updateByPrimaryKey(WxQrcode record);
    
    /**
     * 获取二维码
     *
     * @author smile
     * @data 2016年12月20日
     * @param schema
     * @param ticket
     * @return 
     * @return WxQrcode
     */
    public WxQrcode getQrcodeByTicket(@Param("schema")String schema, @Param("ticket")String ticket);
}