package com.cm.dao.mapper.wechat;

import org.apache.ibatis.annotations.Param;

import com.cm.dao.model.wechat.WxUser;

public interface WxUserMapper {
    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 根据主键删除数据库的记录
     *
     * @param id
     * wechat..wx_user
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 插入数据库记录
     *
     * @param record
     * wechat..wx_user
     */
    int insert(WxUser record);

    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 插入数据库记录
     *
     * @param record
     * wechat..wx_user
     */
    int insertSelective(WxUser record);

    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 根据主键获取一条数据库记录
     *
     * @param id
     * wechat..wx_user
     */
    WxUser selectByPrimaryKey(@Param("schema")String schema,Integer id);

    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 根据主键来更新部分数据库记录
     *
     * @param record
     * wechat..wx_user
     */
    int updateByPrimaryKeySelective(WxUser record);

    /**
     * @author lenovo
     * This element is automatically generated by MyBatis Generator, do not modify. Tue Dec 20 14:01:40 CST 2016
     * 根据主键来更新数据库记录
     *
     * @param record
     * wechat..wx_user
     */
    int updateByPrimaryKey(WxUser record);
    
    /**
     *  根据公众号schema以及openid获取用户信息
     *
     * @author smile
     * @data 2016年12月20日
     * @param schema
     * @param openid
     * @return 
     * @return WxUser
     */
    public WxUser queryUserByOpenID(@Param("schema")String schema, @Param("openid")String openid);
    
    /**
     * 更新用户关注状态
     *
     * @author smile
     * @data 2016年12月20日
     * @param schema 
     * @param openId
     * @param issubscribe  :用户关注状态  0,未关注 1,已关注
     * @return void
     */
    public void updateSubscribeFlag(@Param("schema")String schema, @Param("openid")String openId, @Param("issubscribe")int issubscribe);
    
}